---
# https://caldera.readthedocs.io/en/latest/Installing-Caldera.html
# https://github.com/mitre/caldera/blob/master/Dockerfile
# https://github.com/nodesource/distributions?tab=readme-ov-file#ubuntu-versions

- name: Check that /opt/caldera exists
  stat:
    path: /opt/caldera
  register: stat_result   

- name: Install Caldera on Ubuntu
  ansible.builtin.include_tasks:
    file: install_ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and not stat_result.stat.exists

- name: Install Caldera on Debian 
  ansible.builtin.include_tasks:
    file: install_debian.yml
  when: ansible_distribution == 'Debian' and not stat_result.stat.exists

