---
# https://caldera.readthedocs.io/en/latest/Installing-Caldera.html

- name: Remove /opt/caldera if it exists
  ansible.builtin.file:
    path: /opt/caldera
    state: absent

- name: Check that /opt/caldera exists
  stat:
    path: /opt/caldera
  register: stat_result   

- name: Install Caldera
  ansible.builtin.include_tasks:
    file: caldera.yml
  when: not stat_result.stat.exists
